# Generated by Django 6.0.5 on 2026-05-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qubit', '0004_topic_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
