# Generated by Django 6.0.5 on 2026-06-16 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Qubit', '0006_alter_entry_options_entry_author_vote'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
    ]
