# Generated by Django 6.0.5 on 2026-06-18 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qubit', '0011_alter_entry_options_alter_topic_options_topic_tags_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_topic_like',
        ),
        migrations.RemoveConstraint(
            model_name='like',
            name='unique_user_entry_like',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='joined_date',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'entry')},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reputation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Qubit.entry'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='topic',
        ),
    ]
